spring:
  datasource:
    url: postfresql://${PGHOST}:${PGPORT}/${PGADATABASE}
    username: ${PGUSER}
    password: ${PGPASSWORD}
  jpa:
    open-in-view: false
    hibernate:
      #ddl-auto: create -> apenas na primeira vez rodando o perfil de prd
      ddl-auto: validate